/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 08-Aug-2016 20:18:41 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `wishes` CASCADE
;


CREATE TABLE `wishes`
(
	`w_id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`w_user` INTEGER UNSIGNED NOT NULL,
	`w_book` INTEGER UNSIGNED NOT NULL,
	CONSTRAINT `PK_wishes` PRIMARY KEY (`w_id`)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `wishes` 
 ADD CONSTRAINT `FK_subscriptions_books`
	FOREIGN KEY (`w_book`) REFERENCES `books` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `wishes` 
 ADD CONSTRAINT `FK_subscriptions_users`
	FOREIGN KEY (`w_user`) REFERENCES `users` (`id`) ON DELETE Cascade ON UPDATE Cascade
;


SET FOREIGN_KEY_CHECKS=1 ;
